apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cast_service.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.cast_service.service.type }}
  ports:
    - name: "http"
      port: {{ .Values.cast_service.service.port }}
      targetPort: {{ .Values.cast_service.service.targetPort }}
  selector:
    app: {{ .Values.cast_service.metadata.label }}
