apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.cast_db.pvc.name }}-{{ .Values.releaseVersion }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.cast_db.pvc.storageCassName }}
  accessModes:
    - {{ .Values.cast_db.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.cast_db.pvc.storage }}
