apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.movie_db.secret }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  user: bW92aWVfZGJfdXNlcm5hbWU=
  password: bW92aWVfZGJfcGFzc3dvcmQ=
