apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.movie_service.pvc.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/resource-policy": "keep"
spec:
  storageClassName: {{ .Values.movie_service.pvc.storageClassName }}
  accessModes:
    - {{ .Values.movie_service.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.movie_service.pvc.storage }}
