apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
  labels:
    app: movie-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
      - name: movie-service
        image: {{ .Values.movieService.image }}
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URI
          value: postgresql://{{ .Values.movieDb.postgresUser }}:{{ .Values.movieDb.postgresPassword }}@movie-db/{{ .Values.movieDb.postgresDatabase }}
        - name: CAST_SERVICE_HOST_URL
          value: http://cast-service:8000/api/v1/casts/
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgre-rootpass
              key: password
        command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
  labels:
    app: cast-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
      - name: cast-service
        image: {{ .Values.castService.image }}
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URI
          value: postgresql://{{ .Values.castDb.postgresUser }}:{{ .Values.castDb.postgresPassword }}@cast-db/{{ .Values.castDb.postgresDatabase }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgre-rootpass
              key: password
        command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: {{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config

