apiVersion: v1
kind: Service
metadata:
  name: cast-db
  namespace: test
spec:
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None # Service headless pour un StatefulSet
  selector:
    app: cast-db
