apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
      - name: cast-service
        image: afarah1208/cast-service:latest
        command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
        env:
        - name: DATABASE_URI
          value: "postgresql://cast_db_username:cast_db_password@cast-db.cast-db.svc.cluster.local/cast_db_dev"
        ports:
        - containerPort: 8000
